name: CI

on:
  pull_request:
    paths:
      - 'jpo-deduplicator/**'

jobs:  
  deduplicator-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: 'maven'

      - name: Run tests
        env:
          MAVEN_GITHUB_TOKEN: ${{ secrets.MAVEN_GITHUB_TOKEN }}
          MAVEN_GITHUB_ORG: ${{ github.repository_owner }}
        run: |
          cd $GITHUB_WORKSPACE/jpo-deduplicator
          mvn verify -s ./settings.xml